### ISSUE TITLE
Is there a new home for the SLEP 4.1 manual PDF?

### ISSUE THREAD

**Issue by deborah-chasman** [jiayuzhou/SLEP#1]
I'm not able to locate the manual at http://www.public.asu.edu/~jye02/Software/SLEP/manual.pdf or at http://yelab.net/software/SLEP/manual.pdf. Is there a new home for this document?

Thank you.

**Comment by jiayuzhou** [comment]
Hello, this repository is a personal repo and not the official one. I think the site was down for maintenance.  Please try to contact the leading author: junliu.nt@gmail.com for a manual.
